//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableStockMasuk
    {
        public int idTransaksi { get; set; }
        public Nullable<int> idProduk { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public int qty { get; set; }
        public string tanggal { get; set; }
        public Nullable<int> hargaTransaksi { get; set; }
    
        public virtual tableProduk tableProduk { get; set; }
        public virtual tableSupplier tableSupplier { get; set; }
    }
}
